# Woobe Phase 1 production infrastructure — EC2 + self-hosted Valkey +
# RDS PostgreSQL + S3, no ALB, no NAT Gateway, no managed Redis/Valkey,
# no Kubernetes, no Auto Scaling Group. See infra/terraform/README.md for
# the full design rationale and the Phase 2 migration path.

locals {
  name_prefix = "${lower(var.project)}-${var.environment}"

  common_tags = {
    Project     = var.project
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

module "networking" {
  source = "../../modules/networking"

  name_prefix          = local.name_prefix
  vpc_cidr             = var.vpc_cidr
  public_subnet_cidrs  = var.public_subnet_cidrs
  private_subnet_cidrs = var.private_subnet_cidrs
  tags                 = local.common_tags
}

module "s3" {
  source = "../../modules/s3"

  name_prefix = local.name_prefix
  tags        = local.common_tags
}

# Self-hosted Valkey's auth password. Generated by Terraform, never
# committed anywhere, and handed to the instance at boot only via an
# encrypted SSM parameter the instance role can read — never embedded
# directly in user_data source or in tfvars.
resource "random_password" "valkey" {
  length  = 32
  special = false
}

resource "aws_ssm_parameter" "valkey_password" {
  name  = "/${local.name_prefix}/valkey/password"
  type  = "SecureString"
  value = random_password.valkey.result

  tags = local.common_tags
}

# Public media delivery: Browser -> CloudFront (OAC, HTTPS) -> private S3.
module "cloudfront_media" {
  source = "../../modules/cloudfront-media"

  name_prefix                 = local.name_prefix
  bucket_id                   = module.s3.bucket_id
  bucket_arn                  = module.s3.bucket_arn
  bucket_regional_domain_name = module.s3.bucket_regional_domain_name
  price_class                 = var.media_cdn_price_class
  tags                        = local.common_tags
}

module "security" {
  source = "../../modules/security"

  name_prefix           = local.name_prefix
  vpc_id                = module.networking.vpc_id
  cloudflare_ipv4_cidrs = var.cloudflare_ipv4_cidrs
  allow_http_80         = var.allow_http_80
  tags                  = local.common_tags
}

module "rds" {
  source = "../../modules/rds"

  name_prefix           = local.name_prefix
  private_subnet_ids    = module.networking.private_subnet_ids
  rds_sg_id             = module.security.rds_sg_id
  instance_class        = var.db_instance_class
  allocated_storage_gb  = var.db_allocated_storage_gb
  backup_retention_days = var.db_backup_retention_days
  deletion_protection   = var.db_deletion_protection
  skip_final_snapshot   = var.db_skip_final_snapshot
  db_username           = var.db_username
  db_name               = var.db_name
  tags                  = local.common_tags
}

module "iam" {
  source = "../../modules/iam"

  name_prefix        = local.name_prefix
  s3_bucket_arn      = module.s3.bucket_arn
  valkey_param_arn   = aws_ssm_parameter.valkey_password.arn
  rds_secret_arn     = module.rds.master_user_secret_arn
  ecr_repository_arn = module.ecr.repository_arn
  tags               = local.common_tags
}

# ---- CI/CD: GitHub Actions -> ECR -> EC2 (via SSM), authenticated by OIDC ----
# Independent of the EC2/RDS/Valkey stack above: none of these three modules
# reads an EC2 output, so they can be applied first with
# `terraform apply -target=module.github_oidc` (which pulls in ecr and
# ssm_deploy) — see docs/deployment.md.

module "ecr" {
  source = "../../modules/ecr"

  name                  = "${local.name_prefix}-api"
  image_retention_count = var.ecr_image_retention_count
  tags                  = local.common_tags
}

module "ssm_deploy" {
  source = "../../modules/ssm-deploy"

  name_prefix        = local.name_prefix
  ecr_repository_url = module.ecr.repository_url
  aws_region         = var.aws_region
  tags               = local.common_tags
}

module "github_oidc" {
  source = "../../modules/github-oidc"

  github_repository     = var.github_repository
  github_branch         = var.github_branch
  existing_provider_arn = var.existing_github_oidc_provider_arn
  ecr_repository_arn    = module.ecr.repository_arn
  ssm_document_arn      = module.ssm_deploy.document_arn
  instance_tags         = { Project = var.project, Environment = var.environment }
  tags                  = local.common_tags
}

module "ec2" {
  source = "../../modules/ec2"

  name_prefix               = local.name_prefix
  public_subnet_id          = module.networking.public_subnet_ids[0]
  ec2_sg_id                 = module.security.ec2_sg_id
  iam_instance_profile_name = module.iam.instance_profile_name
  instance_type             = var.ec2_instance_type
  root_volume_size_gb       = var.ec2_root_volume_size_gb
  valkey_param_name         = aws_ssm_parameter.valkey_password.name
  valkey_maxmemory_mb       = var.valkey_maxmemory_mb
  compose_version           = var.compose_version
  aws_region                = var.aws_region
  api_domain                = var.api_domain
  api_port                  = var.api_port
  cloudflare_ipv4_cidrs     = var.cloudflare_ipv4_cidrs
  tags                      = local.common_tags
}

# Prometheus + Grafana + Node Exporter, delivered to the instance through SSM (NOT user_data, so a
# dashboard change never replaces the instance) — see modules/observability/main.tf.
# Loopback-only: no security-group rule and no network resource is added by this module.
module "observability" {
  source = "../../modules/observability"

  name_prefix         = local.name_prefix
  aws_region          = var.aws_region
  instance_id         = module.ec2.instance_id
  ec2_role_name       = module.iam.role_name
  config_dir          = "${path.module}/../../../observability"
  api_port            = var.api_port
  worker_metrics_port = var.worker_metrics_port
  tags                = local.common_tags
}

module "monitoring" {
  source = "../../modules/monitoring"

  name_prefix         = local.name_prefix
  ec2_instance_id     = module.ec2.instance_id
  rds_instance_id     = module.rds.identifier
  valkey_maxmemory_mb = var.valkey_maxmemory_mb
  alert_email         = var.alert_email
  tags                = local.common_tags
}

# S3 Gateway VPC Endpoint — keeps EC2 <-> S3 traffic on the AWS backbone
# instead of routing out via the internet, at no additional cost.
#
# Deliberately NO custom endpoint policy (the default allows all S3 access
# through the endpoint; IAM and bucket policies still decide who may do what).
# An earlier revision restricted it to the media bucket, but with this
# endpoint in the route table ALL of the instance's S3 traffic goes through
# it, including AWS-owned buckets the box depends on: ECR image layers
# (prod-<region>-starport-layer-bucket, needed by every `docker pull` in the
# deploy), the Amazon Linux 2023 package repositories, and SSM. A
# media-bucket-only policy would have made image pulls and dnf fail.
resource "aws_vpc_endpoint" "s3" {
  vpc_id            = module.networking.vpc_id
  service_name      = "com.amazonaws.${var.aws_region}.s3"
  vpc_endpoint_type = "Gateway"
  route_table_ids   = [module.networking.public_route_table_id]

  tags = merge(local.common_tags, { Name = "${local.name_prefix}-s3-endpoint" })
}
