# Woobe Phase 1 production infrastructure — EC2 + self-hosted Valkey +
# RDS PostgreSQL + S3, no ALB, no NAT Gateway, no managed Redis/Valkey,
# no Kubernetes, no Auto Scaling Group. See infra/terraform/README.md for
# the full design rationale and the Phase 2 migration path.

locals {
  name_prefix = "${lower(var.project)}-${var.environment}"

  common_tags = {
    Project     = var.project
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

module "networking" {
  source = "../../modules/networking"

  name_prefix          = local.name_prefix
  vpc_cidr             = var.vpc_cidr
  public_subnet_cidrs  = var.public_subnet_cidrs
  private_subnet_cidrs = var.private_subnet_cidrs
  tags                 = local.common_tags
}

module "s3" {
  source = "../../modules/s3"

  name_prefix = local.name_prefix
  tags        = local.common_tags
}

# Self-hosted Valkey's auth password. Generated by Terraform, never
# committed anywhere, and handed to the instance at boot only via an
# encrypted SSM parameter the instance role can read — never embedded
# directly in user_data source or in tfvars.
resource "random_password" "valkey" {
  length  = 32
  special = false
}

resource "aws_ssm_parameter" "valkey_password" {
  name  = "/${local.name_prefix}/valkey/password"
  type  = "SecureString"
  value = random_password.valkey.result

  tags = local.common_tags
}

module "security" {
  source = "../../modules/security"

  name_prefix           = local.name_prefix
  vpc_id                = module.networking.vpc_id
  cloudflare_ipv4_cidrs = var.cloudflare_ipv4_cidrs
  allow_http_80         = var.allow_http_80
  tags                  = local.common_tags
}

module "rds" {
  source = "../../modules/rds"

  name_prefix           = local.name_prefix
  private_subnet_ids    = module.networking.private_subnet_ids
  rds_sg_id             = module.security.rds_sg_id
  instance_class        = var.db_instance_class
  allocated_storage_gb  = var.db_allocated_storage_gb
  backup_retention_days = var.db_backup_retention_days
  deletion_protection   = var.db_deletion_protection
  skip_final_snapshot   = var.db_skip_final_snapshot
  db_username           = var.db_username
  db_name               = var.db_name
  tags                  = local.common_tags
}

module "iam" {
  source = "../../modules/iam"

  name_prefix      = local.name_prefix
  s3_bucket_arn    = module.s3.bucket_arn
  valkey_param_arn = aws_ssm_parameter.valkey_password.arn
  rds_secret_arn   = module.rds.master_user_secret_arn
  tags             = local.common_tags
}

module "ec2" {
  source = "../../modules/ec2"

  name_prefix               = local.name_prefix
  public_subnet_id          = module.networking.public_subnet_ids[0]
  ec2_sg_id                 = module.security.ec2_sg_id
  iam_instance_profile_name = module.iam.instance_profile_name
  instance_type             = var.ec2_instance_type
  root_volume_size_gb       = var.ec2_root_volume_size_gb
  valkey_param_name         = aws_ssm_parameter.valkey_password.name
  valkey_maxmemory_mb       = var.valkey_maxmemory_mb
  compose_version           = var.compose_version
  aws_region                = var.aws_region
  tags                      = local.common_tags
}

module "monitoring" {
  source = "../../modules/monitoring"

  name_prefix     = local.name_prefix
  ec2_instance_id = module.ec2.instance_id
  rds_instance_id = module.rds.identifier
  alert_email     = var.alert_email
  tags            = local.common_tags
}

# S3 Gateway VPC Endpoint — keeps EC2 <-> S3 media traffic on the AWS
# backbone instead of routing out via the internet, at no additional cost,
# and scoped by policy to only the Woobe media bucket (not all of S3).
resource "aws_vpc_endpoint" "s3" {
  vpc_id            = module.networking.vpc_id
  service_name      = "com.amazonaws.${var.aws_region}.s3"
  vpc_endpoint_type = "Gateway"
  route_table_ids   = [module.networking.public_route_table_id]

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = "*"
      Action    = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:ListBucket"]
      Resource = [
        module.s3.bucket_arn,
        "${module.s3.bucket_arn}/*"
      ]
    }]
  })

  tags = merge(local.common_tags, { Name = "${local.name_prefix}-s3-endpoint" })
}
